// Türkiye İl ve İlçe Verileri
// 81 il ve tüm ilçeler

export const TURKEY_PROVINCES = [
  { id: 1, name: "Adana" },
  { id: 2, name: "Adıyaman" },
  { id: 3, name: "Afyonkarahisar" },
  { id: 4, name: "Ağrı" },
  { id: 5, name: "Amasya" },
  { id: 6, name: "Ankara" },
  { id: 7, name: "Antalya" },
  { id: 8, name: "Artvin" },
  { id: 9, name: "Aydın" },
  { id: 10, name: "Balıkesir" },
  { id: 11, name: "Bilecik" },
  { id: 12, name: "Bingöl" },
  { id: 13, name: "Bitlis" },
  { id: 14, name: "Bolu" },
  { id: 15, name: "Burdur" },
  { id: 16, name: "Bursa" },
  { id: 17, name: "Çanakkale" },
  { id: 18, name: "Çankırı" },
  { id: 19, name: "Çorum" },
  { id: 20, name: "Denizli" },
  { id: 21, name: "Diyarbakır" },
  { id: 22, name: "Edirne" },
  { id: 23, name: "Elazığ" },
  { id: 24, name: "Erzincan" },
  { id: 25, name: "Erzurum" },
  { id: 26, name: "Eskişehir" },
  { id: 27, name: "Gaziantep" },
  { id: 28, name: "Giresun" },
  { id: 29, name: "Gümüşhane" },
  { id: 30, name: "Hakkari" },
  { id: 31, name: "Hatay" },
  { id: 32, name: "Isparta" },
  { id: 33, name: "Mersin" },
  { id: 34, name: "İstanbul" },
  { id: 35, name: "İzmir" },
  { id: 36, name: "Kars" },
  { id: 37, name: "Kastamonu" },
  { id: 38, name: "Kayseri" },
  { id: 39, name: "Kırklareli" },
  { id: 40, name: "Kırşehir" },
  { id: 41, name: "Kocaeli" },
  { id: 42, name: "Konya" },
  { id: 43, name: "Kütahya" },
  { id: 44, name: "Malatya" },
  { id: 45, name: "Manisa" },
  { id: 46, name: "Kahramanmaraş" },
  { id: 47, name: "Mardin" },
  { id: 48, name: "Muğla" },
  { id: 49, name: "Muş" },
  { id: 50, name: "Nevşehir" },
  { id: 51, name: "Niğde" },
  { id: 52, name: "Ordu" },
  { id: 53, name: "Rize" },
  { id: 54, name: "Sakarya" },
  { id: 55, name: "Samsun" },
  { id: 56, name: "Siirt" },
  { id: 57, name: "Sinop" },
  { id: 58, name: "Sivas" },
  { id: 59, name: "Tekirdağ" },
  { id: 60, name: "Tokat" },
  { id: 61, name: "Trabzon" },
  { id: 62, name: "Tunceli" },
  { id: 63, name: "Şanlıurfa" },
  { id: 64, name: "Uşak" },
  { id: 65, name: "Van" },
  { id: 66, name: "Yozgat" },
  { id: 67, name: "Zonguldak" },
  { id: 68, name: "Aksaray" },
  { id: 69, name: "Bayburt" },
  { id: 70, name: "Karaman" },
  { id: 71, name: "Kırıkkale" },
  { id: 72, name: "Batman" },
  { id: 73, name: "Şırnak" },
  { id: 74, name: "Bartın" },
  { id: 75, name: "Ardahan" },
  { id: 76, name: "Iğdır" },
  { id: 77, name: "Yalova" },
  { id: 78, name: "Karabük" },
  { id: 79, name: "Kilis" },
  { id: 80, name: "Osmaniye" },
  { id: 81, name: "Düzce" },
];

export const TURKEY_DISTRICTS = [
  // Adana (1)
  { provinceId: 1, name: "Aladağ" },
  { provinceId: 1, name: "Ceyhan" },
  { provinceId: 1, name: "Çukurova" },
  { provinceId: 1, name: "Feke" },
  { provinceId: 1, name: "İmamoğlu" },
  { provinceId: 1, name: "Karaisalı" },
  { provinceId: 1, name: "Karataş" },
  { provinceId: 1, name: "Kozan" },
  { provinceId: 1, name: "Pozantı" },
  { provinceId: 1, name: "Saimbeyli" },
  { provinceId: 1, name: "Sarıçam" },
  { provinceId: 1, name: "Seyhan" },
  { provinceId: 1, name: "Tufanbeyli" },
  { provinceId: 1, name: "Yumurtalık" },
  { provinceId: 1, name: "Yüreğir" },
  // Adıyaman (2)
  { provinceId: 2, name: "Merkez" },
  { provinceId: 2, name: "Besni" },
  { provinceId: 2, name: "Çelikhan" },
  { provinceId: 2, name: "Gerger" },
  { provinceId: 2, name: "Gölbaşı" },
  { provinceId: 2, name: "Kahta" },
  { provinceId: 2, name: "Samsat" },
  { provinceId: 2, name: "Sincik" },
  { provinceId: 2, name: "Tut" },
  // Afyonkarahisar (3)
  { provinceId: 3, name: "Merkez" },
  { provinceId: 3, name: "Başmakçı" },
  { provinceId: 3, name: "Bayat" },
  { provinceId: 3, name: "Bolvadin" },
  { provinceId: 3, name: "Çay" },
  { provinceId: 3, name: "Çobanlar" },
  { provinceId: 3, name: "Dazkırı" },
  { provinceId: 3, name: "Dinar" },
  { provinceId: 3, name: "Emirdağ" },
  { provinceId: 3, name: "Evciler" },
  { provinceId: 3, name: "Hocalar" },
  { provinceId: 3, name: "İhsaniye" },
  { provinceId: 3, name: "İscehisar" },
  { provinceId: 3, name: "Kızılören" },
  { provinceId: 3, name: "Sandıklı" },
  { provinceId: 3, name: "Sinanpaşa" },
  { provinceId: 3, name: "Sultandağı" },
  { provinceId: 3, name: "Şuhut" },
  // Ağrı (4)
  { provinceId: 4, name: "Merkez" },
  { provinceId: 4, name: "Diyadin" },
  { provinceId: 4, name: "Doğubayazıt" },
  { provinceId: 4, name: "Eleşkirt" },
  { provinceId: 4, name: "Hamur" },
  { provinceId: 4, name: "Patnos" },
  { provinceId: 4, name: "Taşlıçay" },
  { provinceId: 4, name: "Tutak" },
  // Amasya (5)
  { provinceId: 5, name: "Merkez" },
  { provinceId: 5, name: "Göynücek" },
  { provinceId: 5, name: "Gümüşhacıköy" },
  { provinceId: 5, name: "Hamamözü" },
  { provinceId: 5, name: "Merzifon" },
  { provinceId: 5, name: "Suluova" },
  { provinceId: 5, name: "Taşova" },
  // Ankara (6)
  { provinceId: 6, name: "Akyurt" },
  { provinceId: 6, name: "Altındağ" },
  { provinceId: 6, name: "Ayaş" },
  { provinceId: 6, name: "Bala" },
  { provinceId: 6, name: "Beypazarı" },
  { provinceId: 6, name: "Çamlıdere" },
  { provinceId: 6, name: "Çankaya" },
  { provinceId: 6, name: "Çubuk" },
  { provinceId: 6, name: "Elmadağ" },
  { provinceId: 6, name: "Etimesgut" },
  { provinceId: 6, name: "Evren" },
  { provinceId: 6, name: "Gölbaşı" },
  { provinceId: 6, name: "Güdül" },
  { provinceId: 6, name: "Haymana" },
  { provinceId: 6, name: "Kahramankazan" },
  { provinceId: 6, name: "Kalecik" },
  { provinceId: 6, name: "Keçiören" },
  { provinceId: 6, name: "Kızılcahamam" },
  { provinceId: 6, name: "Mamak" },
  { provinceId: 6, name: "Nallıhan" },
  { provinceId: 6, name: "Polatlı" },
  { provinceId: 6, name: "Pursaklar" },
  { provinceId: 6, name: "Sincan" },
  { provinceId: 6, name: "Şereflikoçhisar" },
  { provinceId: 6, name: "Yenimahalle" },
  // Antalya (7)
  { provinceId: 7, name: "Akseki" },
  { provinceId: 7, name: "Aksu" },
  { provinceId: 7, name: "Alanya" },
  { provinceId: 7, name: "Demre" },
  { provinceId: 7, name: "Döşemealtı" },
  { provinceId: 7, name: "Elmalı" },
  { provinceId: 7, name: "Finike" },
  { provinceId: 7, name: "Gazipaşa" },
  { provinceId: 7, name: "Gündoğmuş" },
  { provinceId: 7, name: "İbradı" },
  { provinceId: 7, name: "Kaş" },
  { provinceId: 7, name: "Kemer" },
  { provinceId: 7, name: "Kepez" },
  { provinceId: 7, name: "Konyaaltı" },
  { provinceId: 7, name: "Korkuteli" },
  { provinceId: 7, name: "Kumluca" },
  { provinceId: 7, name: "Manavgat" },
  { provinceId: 7, name: "Muratpaşa" },
  { provinceId: 7, name: "Serik" },
  // Artvin (8)
  { provinceId: 8, name: "Merkez" },
  { provinceId: 8, name: "Ardanuç" },
  { provinceId: 8, name: "Arhavi" },
  { provinceId: 8, name: "Borçka" },
  { provinceId: 8, name: "Hopa" },
  { provinceId: 8, name: "Murgul" },
  { provinceId: 8, name: "Şavşat" },
  { provinceId: 8, name: "Yusufeli" },
  // Aydın (9)
  { provinceId: 9, name: "Bozdoğan" },
  { provinceId: 9, name: "Buharkent" },
  { provinceId: 9, name: "Çine" },
  { provinceId: 9, name: "Didim" },
  { provinceId: 9, name: "Efeler" },
  { provinceId: 9, name: "Germencik" },
  { provinceId: 9, name: "İncirliova" },
  { provinceId: 9, name: "Karacasu" },
  { provinceId: 9, name: "Karpuzlu" },
  { provinceId: 9, name: "Koçarlı" },
  { provinceId: 9, name: "Köşk" },
  { provinceId: 9, name: "Kuşadası" },
  { provinceId: 9, name: "Kuyucak" },
  { provinceId: 9, name: "Nazilli" },
  { provinceId: 9, name: "Söke" },
  { provinceId: 9, name: "Sultanhisar" },
  { provinceId: 9, name: "Yenipazar" },
  // Balıkesir (10)
  { provinceId: 10, name: "Altıeylül" },
  { provinceId: 10, name: "Ayvalık" },
  { provinceId: 10, name: "Balya" },
  { provinceId: 10, name: "Bandırma" },
  { provinceId: 10, name: "Bigadiç" },
  { provinceId: 10, name: "Burhaniye" },
  { provinceId: 10, name: "Dursunbey" },
  { provinceId: 10, name: "Edremit" },
  { provinceId: 10, name: "Erdek" },
  { provinceId: 10, name: "Gömeç" },
  { provinceId: 10, name: "Gönen" },
  { provinceId: 10, name: "Havran" },
  { provinceId: 10, name: "İvrindi" },
  { provinceId: 10, name: "Karesi" },
  { provinceId: 10, name: "Kepsut" },
  { provinceId: 10, name: "Manyas" },
  { provinceId: 10, name: "Marmara" },
  { provinceId: 10, name: "Savaştepe" },
  { provinceId: 10, name: "Sındırgı" },
  { provinceId: 10, name: "Susurluk" },
  // Bilecik (11)
  { provinceId: 11, name: "Merkez" },
  { provinceId: 11, name: "Bozüyük" },
  { provinceId: 11, name: "Gölpazarı" },
  { provinceId: 11, name: "İnhisar" },
  { provinceId: 11, name: "Osmaneli" },
  { provinceId: 11, name: "Pazaryeri" },
  { provinceId: 11, name: "Söğüt" },
  { provinceId: 11, name: "Yenipazar" },
  // Bingöl (12)
  { provinceId: 12, name: "Merkez" },
  { provinceId: 12, name: "Adaklı" },
  { provinceId: 12, name: "Genç" },
  { provinceId: 12, name: "Karlıova" },
  { provinceId: 12, name: "Kiğı" },
  { provinceId: 12, name: "Solhan" },
  { provinceId: 12, name: "Yayladere" },
  { provinceId: 12, name: "Yedisu" },
  // Bitlis (13)
  { provinceId: 13, name: "Merkez" },
  { provinceId: 13, name: "Adilcevaz" },
  { provinceId: 13, name: "Ahlat" },
  { provinceId: 13, name: "Güroymak" },
  { provinceId: 13, name: "Hizan" },
  { provinceId: 13, name: "Mutki" },
  { provinceId: 13, name: "Tatvan" },
  // Bolu (14)
  { provinceId: 14, name: "Merkez" },
  { provinceId: 14, name: "Dörtdivan" },
  { provinceId: 14, name: "Gerede" },
  { provinceId: 14, name: "Göynük" },
  { provinceId: 14, name: "Kıbrıscık" },
  { provinceId: 14, name: "Mengen" },
  { provinceId: 14, name: "Mudurnu" },
  { provinceId: 14, name: "Seben" },
  { provinceId: 14, name: "Yeniçağa" },
  // Burdur (15)
  { provinceId: 15, name: "Merkez" },
  { provinceId: 15, name: "Ağlasun" },
  { provinceId: 15, name: "Altınyayla" },
  { provinceId: 15, name: "Bucak" },
  { provinceId: 15, name: "Çavdır" },
  { provinceId: 15, name: "Çeltikçi" },
  { provinceId: 15, name: "Gölhisar" },
  { provinceId: 15, name: "Karamanlı" },
  { provinceId: 15, name: "Kemer" },
  { provinceId: 15, name: "Tefenni" },
  { provinceId: 15, name: "Yeşilova" },
  // Bursa (16)
  { provinceId: 16, name: "Büyükorhan" },
  { provinceId: 16, name: "Gemlik" },
  { provinceId: 16, name: "Gürsu" },
  { provinceId: 16, name: "Harmancık" },
  { provinceId: 16, name: "İnegöl" },
  { provinceId: 16, name: "İznik" },
  { provinceId: 16, name: "Karacabey" },
  { provinceId: 16, name: "Keles" },
  { provinceId: 16, name: "Kestel" },
  { provinceId: 16, name: "Mudanya" },
  { provinceId: 16, name: "Mustafakemalpaşa" },
  { provinceId: 16, name: "Nilüfer" },
  { provinceId: 16, name: "Orhaneli" },
  { provinceId: 16, name: "Orhangazi" },
  { provinceId: 16, name: "Osmangazi" },
  { provinceId: 16, name: "Yenişehir" },
  { provinceId: 16, name: "Yıldırım" },
  // Çanakkale (17)
  { provinceId: 17, name: "Merkez" },
  { provinceId: 17, name: "Ayvacık" },
  { provinceId: 17, name: "Bayramiç" },
  { provinceId: 17, name: "Biga" },
  { provinceId: 17, name: "Bozcaada" },
  { provinceId: 17, name: "Çan" },
  { provinceId: 17, name: "Eceabat" },
  { provinceId: 17, name: "Ezine" },
  { provinceId: 17, name: "Gelibolu" },
  { provinceId: 17, name: "Gökçeada" },
  { provinceId: 17, name: "Lapseki" },
  { provinceId: 17, name: "Yenice" },
  // Çankırı (18)
  { provinceId: 18, name: "Merkez" },
  { provinceId: 18, name: "Atkaracalar" },
  { provinceId: 18, name: "Bayramören" },
  { provinceId: 18, name: "Çerkeş" },
  { provinceId: 18, name: "Eldivan" },
  { provinceId: 18, name: "Ilgaz" },
  { provinceId: 18, name: "Kızılırmak" },
  { provinceId: 18, name: "Korgun" },
  { provinceId: 18, name: "Kurşunlu" },
  { provinceId: 18, name: "Orta" },
  { provinceId: 18, name: "Şabanözü" },
  { provinceId: 18, name: "Yapraklı" },
  // Çorum (19)
  { provinceId: 19, name: "Merkez" },
  { provinceId: 19, name: "Alaca" },
  { provinceId: 19, name: "Bayat" },
  { provinceId: 19, name: "Boğazkale" },
  { provinceId: 19, name: "Dodurga" },
  { provinceId: 19, name: "İskilip" },
  { provinceId: 19, name: "Kargı" },
  { provinceId: 19, name: "Laçin" },
  { provinceId: 19, name: "Mecitözü" },
  { provinceId: 19, name: "Oğuzlar" },
  { provinceId: 19, name: "Ortaköy" },
  { provinceId: 19, name: "Osmancık" },
  { provinceId: 19, name: "Sungurlu" },
  { provinceId: 19, name: "Uğurludağ" },
  // Denizli (20)
  { provinceId: 20, name: "Acıpayam" },
  { provinceId: 20, name: "Babadağ" },
  { provinceId: 20, name: "Baklan" },
  { provinceId: 20, name: "Bekilli" },
  { provinceId: 20, name: "Beyağaç" },
  { provinceId: 20, name: "Bozkurt" },
  { provinceId: 20, name: "Buldan" },
  { provinceId: 20, name: "Çal" },
  { provinceId: 20, name: "Çameli" },
  { provinceId: 20, name: "Çardak" },
  { provinceId: 20, name: "Çivril" },
  { provinceId: 20, name: "Güney" },
  { provinceId: 20, name: "Honaz" },
  { provinceId: 20, name: "Kale" },
  { provinceId: 20, name: "Merkezefendi" },
  { provinceId: 20, name: "Pamukkale" },
  { provinceId: 20, name: "Sarayköy" },
  { provinceId: 20, name: "Serinhisar" },
  { provinceId: 20, name: "Tavas" },
  // Diyarbakır (21)
  { provinceId: 21, name: "Bağlar" },
  { provinceId: 21, name: "Bismil" },
  { provinceId: 21, name: "Çermik" },
  { provinceId: 21, name: "Çınar" },
  { provinceId: 21, name: "Çüngüş" },
  { provinceId: 21, name: "Dicle" },
  { provinceId: 21, name: "Eğil" },
  { provinceId: 21, name: "Ergani" },
  { provinceId: 21, name: "Hani" },
  { provinceId: 21, name: "Hazro" },
  { provinceId: 21, name: "Kayapınar" },
  { provinceId: 21, name: "Kocaköy" },
  { provinceId: 21, name: "Kulp" },
  { provinceId: 21, name: "Lice" },
  { provinceId: 21, name: "Silvan" },
  { provinceId: 21, name: "Sur" },
  { provinceId: 21, name: "Yenişehir" },
  // Edirne (22)
  { provinceId: 22, name: "Merkez" },
  { provinceId: 22, name: "Enez" },
  { provinceId: 22, name: "Havsa" },
  { provinceId: 22, name: "İpsala" },
  { provinceId: 22, name: "Keşan" },
  { provinceId: 22, name: "Lalapaşa" },
  { provinceId: 22, name: "Meriç" },
  { provinceId: 22, name: "Süloğlu" },
  { provinceId: 22, name: "Uzunköprü" },
  // Elazığ (23)
  { provinceId: 23, name: "Merkez" },
  { provinceId: 23, name: "Ağın" },
  { provinceId: 23, name: "Alacakaya" },
  { provinceId: 23, name: "Arıcak" },
  { provinceId: 23, name: "Baskil" },
  { provinceId: 23, name: "Karakoçan" },
  { provinceId: 23, name: "Keban" },
  { provinceId: 23, name: "Kovancılar" },
  { provinceId: 23, name: "Maden" },
  { provinceId: 23, name: "Palu" },
  { provinceId: 23, name: "Sivrice" },
  // Erzincan (24)
  { provinceId: 24, name: "Merkez" },
  { provinceId: 24, name: "Çayırlı" },
  { provinceId: 24, name: "İliç" },
  { provinceId: 24, name: "Kemah" },
  { provinceId: 24, name: "Kemaliye" },
  { provinceId: 24, name: "Otlukbeli" },
  { provinceId: 24, name: "Refahiye" },
  { provinceId: 24, name: "Tercan" },
  { provinceId: 24, name: "Üzümlü" },
  // Erzurum (25)
  { provinceId: 25, name: "Aziziye" },
  { provinceId: 25, name: "Aşkale" },
  { provinceId: 25, name: "Çat" },
  { provinceId: 25, name: "Hınıs" },
  { provinceId: 25, name: "Horasan" },
  { provinceId: 25, name: "İspir" },
  { provinceId: 25, name: "Karaçoban" },
  { provinceId: 25, name: "Karayazı" },
  { provinceId: 25, name: "Köprüköy" },
  { provinceId: 25, name: "Narman" },
  { provinceId: 25, name: "Oltu" },
  { provinceId: 25, name: "Olur" },
  { provinceId: 25, name: "Palandöken" },
  { provinceId: 25, name: "Pasinler" },
  { provinceId: 25, name: "Pazaryolu" },
  { provinceId: 25, name: "Şenkaya" },
  { provinceId: 25, name: "Tekman" },
  { provinceId: 25, name: "Tortum" },
  { provinceId: 25, name: "Uzundere" },
  { provinceId: 25, name: "Yakutiye" },
  // Eskişehir (26)
  { provinceId: 26, name: "Alpu" },
  { provinceId: 26, name: "Beylikova" },
  { provinceId: 26, name: "Çifteler" },
  { provinceId: 26, name: "Günyüzü" },
  { provinceId: 26, name: "Han" },
  { provinceId: 26, name: "İnönü" },
  { provinceId: 26, name: "Mahmudiye" },
  { provinceId: 26, name: "Mihalgazi" },
  { provinceId: 26, name: "Mihalıççık" },
  { provinceId: 26, name: "Odunpazarı" },
  { provinceId: 26, name: "Sarıcakaya" },
  { provinceId: 26, name: "Seyitgazi" },
  { provinceId: 26, name: "Sivrihisar" },
  { provinceId: 26, name: "Tepebaşı" },
  // Gaziantep (27)
  { provinceId: 27, name: "Araban" },
  { provinceId: 27, name: "İslahiye" },
  { provinceId: 27, name: "Karkamış" },
  { provinceId: 27, name: "Nizip" },
  { provinceId: 27, name: "Nurdağı" },
  { provinceId: 27, name: "Oğuzeli" },
  { provinceId: 27, name: "Şahinbey" },
  { provinceId: 27, name: "Şehitkamil" },
  { provinceId: 27, name: "Yavuzeli" },
  // Giresun (28)
  { provinceId: 28, name: "Merkez" },
  { provinceId: 28, name: "Alucra" },
  { provinceId: 28, name: "Bulancak" },
  { provinceId: 28, name: "Çamoluk" },
  { provinceId: 28, name: "Çanakçı" },
  { provinceId: 28, name: "Dereli" },
  { provinceId: 28, name: "Doğankent" },
  { provinceId: 28, name: "Espiye" },
  { provinceId: 28, name: "Eynesil" },
  { provinceId: 28, name: "Görele" },
  { provinceId: 28, name: "Güce" },
  { provinceId: 28, name: "Keşap" },
  { provinceId: 28, name: "Piraziz" },
  { provinceId: 28, name: "Şebinkarahisar" },
  { provinceId: 28, name: "Tirebolu" },
  { provinceId: 28, name: "Yağlıdere" },
  // Gümüşhane (29)
  { provinceId: 29, name: "Merkez" },
  { provinceId: 29, name: "Kelkit" },
  { provinceId: 29, name: "Köse" },
  { provinceId: 29, name: "Kürtün" },
  { provinceId: 29, name: "Şiran" },
  { provinceId: 29, name: "Torul" },
  // Hakkari (30)
  { provinceId: 30, name: "Merkez" },
  { provinceId: 30, name: "Çukurca" },
  { provinceId: 30, name: "Şemdinli" },
  { provinceId: 30, name: "Yüksekova" },
  // Hatay (31)
  { provinceId: 31, name: "Altınözü" },
  { provinceId: 31, name: "Antakya" },
  { provinceId: 31, name: "Arsuz" },
  { provinceId: 31, name: "Belen" },
  { provinceId: 31, name: "Defne" },
  { provinceId: 31, name: "Dörtyol" },
  { provinceId: 31, name: "Erzin" },
  { provinceId: 31, name: "Hassa" },
  { provinceId: 31, name: "İskenderun" },
  { provinceId: 31, name: "Kırıkhan" },
  { provinceId: 31, name: "Kumlu" },
  { provinceId: 31, name: "Payas" },
  { provinceId: 31, name: "Reyhanlı" },
  { provinceId: 31, name: "Samandağ" },
  { provinceId: 31, name: "Yayladağı" },
  // Isparta (32)
  { provinceId: 32, name: "Merkez" },
  { provinceId: 32, name: "Aksu" },
  { provinceId: 32, name: "Atabey" },
  { provinceId: 32, name: "Eğirdir" },
  { provinceId: 32, name: "Gelendost" },
  { provinceId: 32, name: "Gönen" },
  { provinceId: 32, name: "Keçiborlu" },
  { provinceId: 32, name: "Senirkent" },
  { provinceId: 32, name: "Sütçüler" },
  { provinceId: 32, name: "Şarkikaraağaç" },
  { provinceId: 32, name: "Uluborlu" },
  { provinceId: 32, name: "Yalvaç" },
  { provinceId: 32, name: "Yenişarbademli" },
  // Mersin (33)
  { provinceId: 33, name: "Akdeniz" },
  { provinceId: 33, name: "Anamur" },
  { provinceId: 33, name: "Aydıncık" },
  { provinceId: 33, name: "Bozyazı" },
  { provinceId: 33, name: "Çamlıyayla" },
  { provinceId: 33, name: "Erdemli" },
  { provinceId: 33, name: "Gülnar" },
  { provinceId: 33, name: "Mezitli" },
  { provinceId: 33, name: "Mut" },
  { provinceId: 33, name: "Silifke" },
  { provinceId: 33, name: "Tarsus" },
  { provinceId: 33, name: "Toroslar" },
  { provinceId: 33, name: "Yenişehir" },
  // İstanbul (34)
  { provinceId: 34, name: "Adalar" },
  { provinceId: 34, name: "Arnavutköy" },
  { provinceId: 34, name: "Ataşehir" },
  { provinceId: 34, name: "Avcılar" },
  { provinceId: 34, name: "Bağcılar" },
  { provinceId: 34, name: "Bahçelievler" },
  { provinceId: 34, name: "Bakırköy" },
  { provinceId: 34, name: "Başakşehir" },
  { provinceId: 34, name: "Bayrampaşa" },
  { provinceId: 34, name: "Beşiktaş" },
  { provinceId: 34, name: "Beykoz" },
  { provinceId: 34, name: "Beylikdüzü" },
  { provinceId: 34, name: "Beyoğlu" },
  { provinceId: 34, name: "Büyükçekmece" },
  { provinceId: 34, name: "Çatalca" },
  { provinceId: 34, name: "Çekmeköy" },
  { provinceId: 34, name: "Esenler" },
  { provinceId: 34, name: "Esenyurt" },
  { provinceId: 34, name: "Eyüpsultan" },
  { provinceId: 34, name: "Fatih" },
  { provinceId: 34, name: "Gaziosmanpaşa" },
  { provinceId: 34, name: "Güngören" },
  { provinceId: 34, name: "Kadıköy" },
  { provinceId: 34, name: "Kağıthane" },
  { provinceId: 34, name: "Kartal" },
  { provinceId: 34, name: "Küçükçekmece" },
  { provinceId: 34, name: "Maltepe" },
  { provinceId: 34, name: "Pendik" },
  { provinceId: 34, name: "Sancaktepe" },
  { provinceId: 34, name: "Sarıyer" },
  { provinceId: 34, name: "Silivri" },
  { provinceId: 34, name: "Sultanbeyli" },
  { provinceId: 34, name: "Sultangazi" },
  { provinceId: 34, name: "Şile" },
  { provinceId: 34, name: "Şişli" },
  { provinceId: 34, name: "Tuzla" },
  { provinceId: 34, name: "Ümraniye" },
  { provinceId: 34, name: "Üsküdar" },
  { provinceId: 34, name: "Zeytinburnu" },
  // İzmir (35)
  { provinceId: 35, name: "Aliağa" },
  { provinceId: 35, name: "Balçova" },
  { provinceId: 35, name: "Bayındır" },
  { provinceId: 35, name: "Bayraklı" },
  { provinceId: 35, name: "Bergama" },
  { provinceId: 35, name: "Beydağ" },
  { provinceId: 35, name: "Bornova" },
  { provinceId: 35, name: "Buca" },
  { provinceId: 35, name: "Çeşme" },
  { provinceId: 35, name: "Çiğli" },
  { provinceId: 35, name: "Dikili" },
  { provinceId: 35, name: "Foça" },
  { provinceId: 35, name: "Gaziemir" },
  { provinceId: 35, name: "Güzelbahçe" },
  { provinceId: 35, name: "Karabağlar" },
  { provinceId: 35, name: "Karaburun" },
  { provinceId: 35, name: "Karşıyaka" },
  { provinceId: 35, name: "Kemalpaşa" },
  { provinceId: 35, name: "Kınık" },
  { provinceId: 35, name: "Kiraz" },
  { provinceId: 35, name: "Konak" },
  { provinceId: 35, name: "Menderes" },
  { provinceId: 35, name: "Menemen" },
  { provinceId: 35, name: "Narlıdere" },
  { provinceId: 35, name: "Ödemiş" },
  { provinceId: 35, name: "Seferihisar" },
  { provinceId: 35, name: "Selçuk" },
  { provinceId: 35, name: "Tire" },
  { provinceId: 35, name: "Torbalı" },
  { provinceId: 35, name: "Urla" },
  // Kars (36)
  { provinceId: 36, name: "Merkez" },
  { provinceId: 36, name: "Akyaka" },
  { provinceId: 36, name: "Arpaçay" },
  { provinceId: 36, name: "Digor" },
  { provinceId: 36, name: "Kağızman" },
  { provinceId: 36, name: "Sarıkamış" },
  { provinceId: 36, name: "Selim" },
  { provinceId: 36, name: "Susuz" },
  // Kastamonu (37)
  { provinceId: 37, name: "Merkez" },
  { provinceId: 37, name: "Abana" },
  { provinceId: 37, name: "Ağlı" },
  { provinceId: 37, name: "Araç" },
  { provinceId: 37, name: "Azdavay" },
  { provinceId: 37, name: "Bozkurt" },
  { provinceId: 37, name: "Cide" },
  { provinceId: 37, name: "Çatalzeytin" },
  { provinceId: 37, name: "Daday" },
  { provinceId: 37, name: "Devrekani" },
  { provinceId: 37, name: "Doğanyurt" },
  { provinceId: 37, name: "Hanönü" },
  { provinceId: 37, name: "İhsangazi" },
  { provinceId: 37, name: "İnebolu" },
  { provinceId: 37, name: "Küre" },
  { provinceId: 37, name: "Pınarbaşı" },
  { provinceId: 37, name: "Seydiler" },
  { provinceId: 37, name: "Şenpazar" },
  { provinceId: 37, name: "Taşköprü" },
  { provinceId: 37, name: "Tosya" },
  // Kayseri (38)
  { provinceId: 38, name: "Akkışla" },
  { provinceId: 38, name: "Bünyan" },
  { provinceId: 38, name: "Develi" },
  { provinceId: 38, name: "Felahiye" },
  { provinceId: 38, name: "Hacılar" },
  { provinceId: 38, name: "İncesu" },
  { provinceId: 38, name: "Kocasinan" },
  { provinceId: 38, name: "Melikgazi" },
  { provinceId: 38, name: "Özvatan" },
  { provinceId: 38, name: "Pınarbaşı" },
  { provinceId: 38, name: "Sarıoğlan" },
  { provinceId: 38, name: "Sarız" },
  { provinceId: 38, name: "Talas" },
  { provinceId: 38, name: "Tomarza" },
  { provinceId: 38, name: "Yahyalı" },
  { provinceId: 38, name: "Yeşilhisar" },
  // Kırklareli (39)
  { provinceId: 39, name: "Merkez" },
  { provinceId: 39, name: "Babaeski" },
  { provinceId: 39, name: "Demirköy" },
  { provinceId: 39, name: "Kofçaz" },
  { provinceId: 39, name: "Lüleburgaz" },
  { provinceId: 39, name: "Pehlivanköy" },
  { provinceId: 39, name: "Pınarhisar" },
  { provinceId: 39, name: "Vize" },
  // Kırşehir (40)
  { provinceId: 40, name: "Merkez" },
  { provinceId: 40, name: "Akçakent" },
  { provinceId: 40, name: "Akpınar" },
  { provinceId: 40, name: "Boztepe" },
  { provinceId: 40, name: "Çiçekdağı" },
  { provinceId: 40, name: "Kaman" },
  { provinceId: 40, name: "Mucur" },
  // Kocaeli (41)
  { provinceId: 41, name: "Başiskele" },
  { provinceId: 41, name: "Çayırova" },
  { provinceId: 41, name: "Darıca" },
  { provinceId: 41, name: "Derince" },
  { provinceId: 41, name: "Dilovası" },
  { provinceId: 41, name: "Gebze" },
  { provinceId: 41, name: "Gölcük" },
  { provinceId: 41, name: "İzmit" },
  { provinceId: 41, name: "Kandıra" },
  { provinceId: 41, name: "Karamürsel" },
  { provinceId: 41, name: "Kartepe" },
  { provinceId: 41, name: "Körfez" },
  // Konya (42)
  { provinceId: 42, name: "Ahırlı" },
  { provinceId: 42, name: "Akören" },
  { provinceId: 42, name: "Akşehir" },
  { provinceId: 42, name: "Altınekin" },
  { provinceId: 42, name: "Beyşehir" },
  { provinceId: 42, name: "Bozkır" },
  { provinceId: 42, name: "Cihanbeyli" },
  { provinceId: 42, name: "Çeltik" },
  { provinceId: 42, name: "Çumra" },
  { provinceId: 42, name: "Derbent" },
  { provinceId: 42, name: "Derebucak" },
  { provinceId: 42, name: "Doğanhisar" },
  { provinceId: 42, name: "Emirgazi" },
  { provinceId: 42, name: "Ereğli" },
  { provinceId: 42, name: "Güneysınır" },
  { provinceId: 42, name: "Hadim" },
  { provinceId: 42, name: "Halkapınar" },
  { provinceId: 42, name: "Hüyük" },
  { provinceId: 42, name: "Ilgın" },
  { provinceId: 42, name: "Kadınhanı" },
  { provinceId: 42, name: "Karapınar" },
  { provinceId: 42, name: "Karatay" },
  { provinceId: 42, name: "Kulu" },
  { provinceId: 42, name: "Meram" },
  { provinceId: 42, name: "Sarayönü" },
  { provinceId: 42, name: "Selçuklu" },
  { provinceId: 42, name: "Seydişehir" },
  { provinceId: 42, name: "Taşkent" },
  { provinceId: 42, name: "Tuzlukçu" },
  { provinceId: 42, name: "Yalıhüyük" },
  { provinceId: 42, name: "Yunak" },
  // Kütahya (43)
  { provinceId: 43, name: "Merkez" },
  { provinceId: 43, name: "Altıntaş" },
  { provinceId: 43, name: "Aslanapa" },
  { provinceId: 43, name: "Çavdarhisar" },
  { provinceId: 43, name: "Domaniç" },
  { provinceId: 43, name: "Dumlupınar" },
  { provinceId: 43, name: "Emet" },
  { provinceId: 43, name: "Gediz" },
  { provinceId: 43, name: "Hisarcık" },
  { provinceId: 43, name: "Pazarlar" },
  { provinceId: 43, name: "Simav" },
  { provinceId: 43, name: "Şaphane" },
  { provinceId: 43, name: "Tavşanlı" },
  // Malatya (44)
  { provinceId: 44, name: "Akçadağ" },
  { provinceId: 44, name: "Arapgir" },
  { provinceId: 44, name: "Arguvan" },
  { provinceId: 44, name: "Battalgazi" },
  { provinceId: 44, name: "Darende" },
  { provinceId: 44, name: "Doğanşehir" },
  { provinceId: 44, name: "Doğanyol" },
  { provinceId: 44, name: "Hekimhan" },
  { provinceId: 44, name: "Kale" },
  { provinceId: 44, name: "Kuluncak" },
  { provinceId: 44, name: "Pütürge" },
  { provinceId: 44, name: "Yazıhan" },
  { provinceId: 44, name: "Yeşilyurt" },
  // Manisa (45)
  { provinceId: 45, name: "Ahmetli" },
  { provinceId: 45, name: "Akhisar" },
  { provinceId: 45, name: "Alaşehir" },
  { provinceId: 45, name: "Demirci" },
  { provinceId: 45, name: "Gölmarmara" },
  { provinceId: 45, name: "Gördes" },
  { provinceId: 45, name: "Kırkağaç" },
  { provinceId: 45, name: "Köprübaşı" },
  { provinceId: 45, name: "Kula" },
  { provinceId: 45, name: "Salihli" },
  { provinceId: 45, name: "Sarıgöl" },
  { provinceId: 45, name: "Saruhanlı" },
  { provinceId: 45, name: "Selendi" },
  { provinceId: 45, name: "Soma" },
  { provinceId: 45, name: "Şehzadeler" },
  { provinceId: 45, name: "Turgutlu" },
  { provinceId: 45, name: "Yunusemre" },
  // Kahramanmaraş (46)
  { provinceId: 46, name: "Afşin" },
  { provinceId: 46, name: "Andırın" },
  { provinceId: 46, name: "Çağlayancerit" },
  { provinceId: 46, name: "Dulkadiroğlu" },
  { provinceId: 46, name: "Ekinözü" },
  { provinceId: 46, name: "Elbistan" },
  { provinceId: 46, name: "Göksun" },
  { provinceId: 46, name: "Nurhak" },
  { provinceId: 46, name: "Onikişubat" },
  { provinceId: 46, name: "Pazarcık" },
  { provinceId: 46, name: "Türkoğlu" },
  // Mardin (47)
  { provinceId: 47, name: "Artuklu" },
  { provinceId: 47, name: "Dargeçit" },
  { provinceId: 47, name: "Derik" },
  { provinceId: 47, name: "Kızıltepe" },
  { provinceId: 47, name: "Mazıdağı" },
  { provinceId: 47, name: "Midyat" },
  { provinceId: 47, name: "Nusaybin" },
  { provinceId: 47, name: "Ömerli" },
  { provinceId: 47, name: "Savur" },
  { provinceId: 47, name: "Yeşilli" },
  // Muğla (48)
  { provinceId: 48, name: "Bodrum" },
  { provinceId: 48, name: "Dalaman" },
  { provinceId: 48, name: "Datça" },
  { provinceId: 48, name: "Fethiye" },
  { provinceId: 48, name: "Kavaklıdere" },
  { provinceId: 48, name: "Köyceğiz" },
  { provinceId: 48, name: "Marmaris" },
  { provinceId: 48, name: "Menteşe" },
  { provinceId: 48, name: "Milas" },
  { provinceId: 48, name: "Ortaca" },
  { provinceId: 48, name: "Seydikemer" },
  { provinceId: 48, name: "Ula" },
  { provinceId: 48, name: "Yatağan" },
  // Muş (49)
  { provinceId: 49, name: "Merkez" },
  { provinceId: 49, name: "Bulanık" },
  { provinceId: 49, name: "Hasköy" },
  { provinceId: 49, name: "Korkut" },
  { provinceId: 49, name: "Malazgirt" },
  { provinceId: 49, name: "Varto" },
  // Nevşehir (50)
  { provinceId: 50, name: "Merkez" },
  { provinceId: 50, name: "Acıgöl" },
  { provinceId: 50, name: "Avanos" },
  { provinceId: 50, name: "Derinkuyu" },
  { provinceId: 50, name: "Gülşehir" },
  { provinceId: 50, name: "Hacıbektaş" },
  { provinceId: 50, name: "Kozaklı" },
  { provinceId: 50, name: "Ürgüp" },
  // Niğde (51)
  { provinceId: 51, name: "Merkez" },
  { provinceId: 51, name: "Altunhisar" },
  { provinceId: 51, name: "Bor" },
  { provinceId: 51, name: "Çamardı" },
  { provinceId: 51, name: "Çiftlik" },
  { provinceId: 51, name: "Ulukışla" },
  // Ordu (52)
  { provinceId: 52, name: "Akkuş" },
  { provinceId: 52, name: "Altınordu" },
  { provinceId: 52, name: "Aybastı" },
  { provinceId: 52, name: "Çamaş" },
  { provinceId: 52, name: "Çatalpınar" },
  { provinceId: 52, name: "Çaybaşı" },
  { provinceId: 52, name: "Fatsa" },
  { provinceId: 52, name: "Gölköy" },
  { provinceId: 52, name: "Gülyalı" },
  { provinceId: 52, name: "Gürgentepe" },
  { provinceId: 52, name: "İkizce" },
  { provinceId: 52, name: "Kabadüz" },
  { provinceId: 52, name: "Kabataş" },
  { provinceId: 52, name: "Korgan" },
  { provinceId: 52, name: "Kumru" },
  { provinceId: 52, name: "Mesudiye" },
  { provinceId: 52, name: "Perşembe" },
  { provinceId: 52, name: "Ulubey" },
  { provinceId: 52, name: "Ünye" },
  // Rize (53)
  { provinceId: 53, name: "Merkez" },
  { provinceId: 53, name: "Ardeşen" },
  { provinceId: 53, name: "Çamlıhemşin" },
  { provinceId: 53, name: "Çayeli" },
  { provinceId: 53, name: "Derepazarı" },
  { provinceId: 53, name: "Fındıklı" },
  { provinceId: 53, name: "Güneysu" },
  { provinceId: 53, name: "Hemşin" },
  { provinceId: 53, name: "İkizdere" },
  { provinceId: 53, name: "İyidere" },
  { provinceId: 53, name: "Kalkandere" },
  { provinceId: 53, name: "Pazar" },
  // Sakarya (54)
  { provinceId: 54, name: "Adapazarı" },
  { provinceId: 54, name: "Akyazı" },
  { provinceId: 54, name: "Arifiye" },
  { provinceId: 54, name: "Erenler" },
  { provinceId: 54, name: "Ferizli" },
  { provinceId: 54, name: "Geyve" },
  { provinceId: 54, name: "Hendek" },
  { provinceId: 54, name: "Karapürçek" },
  { provinceId: 54, name: "Karasu" },
  { provinceId: 54, name: "Kaynarca" },
  { provinceId: 54, name: "Kocaali" },
  { provinceId: 54, name: "Pamukova" },
  { provinceId: 54, name: "Sapanca" },
  { provinceId: 54, name: "Serdivan" },
  { provinceId: 54, name: "Söğütlü" },
  { provinceId: 54, name: "Taraklı" },
  // Samsun (55)
  { provinceId: 55, name: "Alaçam" },
  { provinceId: 55, name: "Asarcık" },
  { provinceId: 55, name: "Atakum" },
  { provinceId: 55, name: "Ayvacık" },
  { provinceId: 55, name: "Bafra" },
  { provinceId: 55, name: "Canik" },
  { provinceId: 55, name: "Çarşamba" },
  { provinceId: 55, name: "Havza" },
  { provinceId: 55, name: "İlkadım" },
  { provinceId: 55, name: "Kavak" },
  { provinceId: 55, name: "Ladik" },
  { provinceId: 55, name: "Ondokuzmayıs" },
  { provinceId: 55, name: "Salıpazarı" },
  { provinceId: 55, name: "Tekkeköy" },
  { provinceId: 55, name: "Terme" },
  { provinceId: 55, name: "Vezirköprü" },
  { provinceId: 55, name: "Yakakent" },
  // Siirt (56)
  { provinceId: 56, name: "Merkez" },
  { provinceId: 56, name: "Baykan" },
  { provinceId: 56, name: "Eruh" },
  { provinceId: 56, name: "Kurtalan" },
  { provinceId: 56, name: "Pervari" },
  { provinceId: 56, name: "Şirvan" },
  { provinceId: 56, name: "Tillo" },
  // Sinop (57)
  { provinceId: 57, name: "Merkez" },
  { provinceId: 57, name: "Ayancık" },
  { provinceId: 57, name: "Boyabat" },
  { provinceId: 57, name: "Dikmen" },
  { provinceId: 57, name: "Durağan" },
  { provinceId: 57, name: "Erfelek" },
  { provinceId: 57, name: "Gerze" },
  { provinceId: 57, name: "Saraydüzü" },
  { provinceId: 57, name: "Türkeli" },
  // Sivas (58)
  { provinceId: 58, name: "Merkez" },
  { provinceId: 58, name: "Akıncılar" },
  { provinceId: 58, name: "Altınyayla" },
  { provinceId: 58, name: "Divriği" },
  { provinceId: 58, name: "Doğanşar" },
  { provinceId: 58, name: "Gemerek" },
  { provinceId: 58, name: "Gölova" },
  { provinceId: 58, name: "Gürün" },
  { provinceId: 58, name: "Hafik" },
  { provinceId: 58, name: "İmranlı" },
  { provinceId: 58, name: "Kangal" },
  { provinceId: 58, name: "Koyulhisar" },
  { provinceId: 58, name: "Suşehri" },
  { provinceId: 58, name: "Şarkışla" },
  { provinceId: 58, name: "Ulaş" },
  { provinceId: 58, name: "Yıldızeli" },
  { provinceId: 58, name: "Zara" },
  // Tekirdağ (59)
  { provinceId: 59, name: "Çerkezköy" },
  { provinceId: 59, name: "Çorlu" },
  { provinceId: 59, name: "Ergene" },
  { provinceId: 59, name: "Hayrabolu" },
  { provinceId: 59, name: "Kapaklı" },
  { provinceId: 59, name: "Malkara" },
  { provinceId: 59, name: "Marmaraereğlisi" },
  { provinceId: 59, name: "Muratlı" },
  { provinceId: 59, name: "Saray" },
  { provinceId: 59, name: "Süleymanpaşa" },
  { provinceId: 59, name: "Şarköy" },
  // Tokat (60)
  { provinceId: 60, name: "Merkez" },
  { provinceId: 60, name: "Almus" },
  { provinceId: 60, name: "Artova" },
  { provinceId: 60, name: "Başçiftlik" },
  { provinceId: 60, name: "Erbaa" },
  { provinceId: 60, name: "Niksar" },
  { provinceId: 60, name: "Pazar" },
  { provinceId: 60, name: "Reşadiye" },
  { provinceId: 60, name: "Sulusaray" },
  { provinceId: 60, name: "Turhal" },
  { provinceId: 60, name: "Yeşilyurt" },
  { provinceId: 60, name: "Zile" },
  // Trabzon (61)
  { provinceId: 61, name: "Akçaabat" },
  { provinceId: 61, name: "Araklı" },
  { provinceId: 61, name: "Arsin" },
  { provinceId: 61, name: "Beşikdüzü" },
  { provinceId: 61, name: "Çarşıbaşı" },
  { provinceId: 61, name: "Çaykara" },
  { provinceId: 61, name: "Dernekpazarı" },
  { provinceId: 61, name: "Düzköy" },
  { provinceId: 61, name: "Hayrat" },
  { provinceId: 61, name: "Köprübaşı" },
  { provinceId: 61, name: "Maçka" },
  { provinceId: 61, name: "Of" },
  { provinceId: 61, name: "Ortahisar" },
  { provinceId: 61, name: "Sürmene" },
  { provinceId: 61, name: "Şalpazarı" },
  { provinceId: 61, name: "Tonya" },
  { provinceId: 61, name: "Vakfıkebir" },
  { provinceId: 61, name: "Yomra" },
  // Tunceli (62)
  { provinceId: 62, name: "Merkez" },
  { provinceId: 62, name: "Çemişgezek" },
  { provinceId: 62, name: "Hozat" },
  { provinceId: 62, name: "Mazgirt" },
  { provinceId: 62, name: "Nazımiye" },
  { provinceId: 62, name: "Ovacık" },
  { provinceId: 62, name: "Pertek" },
  { provinceId: 62, name: "Pülümür" },
  // Şanlıurfa (63)
  { provinceId: 63, name: "Akçakale" },
  { provinceId: 63, name: "Birecik" },
  { provinceId: 63, name: "Bozova" },
  { provinceId: 63, name: "Ceylanpınar" },
  { provinceId: 63, name: "Eyyübiye" },
  { provinceId: 63, name: "Halfeti" },
  { provinceId: 63, name: "Haliliye" },
  { provinceId: 63, name: "Harran" },
  { provinceId: 63, name: "Hilvan" },
  { provinceId: 63, name: "Karaköprü" },
  { provinceId: 63, name: "Siverek" },
  { provinceId: 63, name: "Suruç" },
  { provinceId: 63, name: "Viranşehir" },
  // Uşak (64)
  { provinceId: 64, name: "Merkez" },
  { provinceId: 64, name: "Banaz" },
  { provinceId: 64, name: "Eşme" },
  { provinceId: 64, name: "Karahallı" },
  { provinceId: 64, name: "Sivaslı" },
  { provinceId: 64, name: "Ulubey" },
  // Van (65)
  { provinceId: 65, name: "Bahçesaray" },
  { provinceId: 65, name: "Başkale" },
  { provinceId: 65, name: "Çaldıran" },
  { provinceId: 65, name: "Çatak" },
  { provinceId: 65, name: "Edremit" },
  { provinceId: 65, name: "Erciş" },
  { provinceId: 65, name: "Gevaş" },
  { provinceId: 65, name: "Gürpınar" },
  { provinceId: 65, name: "İpekyolu" },
  { provinceId: 65, name: "Muradiye" },
  { provinceId: 65, name: "Özalp" },
  { provinceId: 65, name: "Saray" },
  { provinceId: 65, name: "Tuşba" },
  // Yozgat (66)
  { provinceId: 66, name: "Merkez" },
  { provinceId: 66, name: "Akdağmadeni" },
  { provinceId: 66, name: "Aydıncık" },
  { provinceId: 66, name: "Boğazlıyan" },
  { provinceId: 66, name: "Çandır" },
  { provinceId: 66, name: "Çayıralan" },
  { provinceId: 66, name: "Çekerek" },
  { provinceId: 66, name: "Kadışehri" },
  { provinceId: 66, name: "Saraykent" },
  { provinceId: 66, name: "Sarıkaya" },
  { provinceId: 66, name: "Sorgun" },
  { provinceId: 66, name: "Şefaatli" },
  { provinceId: 66, name: "Yenifakılı" },
  { provinceId: 66, name: "Yerköy" },
  // Zonguldak (67)
  { provinceId: 67, name: "Merkez" },
  { provinceId: 67, name: "Alaplı" },
  { provinceId: 67, name: "Çaycuma" },
  { provinceId: 67, name: "Devrek" },
  { provinceId: 67, name: "Gökçebey" },
  { provinceId: 67, name: "Kilimli" },
  { provinceId: 67, name: "Kozlu" },
  { provinceId: 67, name: "Ereğli" },
  // Aksaray (68)
  { provinceId: 68, name: "Merkez" },
  { provinceId: 68, name: "Ağaçören" },
  { provinceId: 68, name: "Eskil" },
  { provinceId: 68, name: "Gülağaç" },
  { provinceId: 68, name: "Güzelyurt" },
  { provinceId: 68, name: "Ortaköy" },
  { provinceId: 68, name: "Sarıyahşi" },
  // Bayburt (69)
  { provinceId: 69, name: "Merkez" },
  { provinceId: 69, name: "Aydıntepe" },
  { provinceId: 69, name: "Demirözü" },
  // Karaman (70)
  { provinceId: 70, name: "Merkez" },
  { provinceId: 70, name: "Ayrancı" },
  { provinceId: 70, name: "Başyayla" },
  { provinceId: 70, name: "Ermenek" },
  { provinceId: 70, name: "Kazımkarabekir" },
  { provinceId: 70, name: "Sarıveliler" },
  // Kırıkkale (71)
  { provinceId: 71, name: "Merkez" },
  { provinceId: 71, name: "Bahşili" },
  { provinceId: 71, name: "Balışeyh" },
  { provinceId: 71, name: "Çelebi" },
  { provinceId: 71, name: "Delice" },
  { provinceId: 71, name: "Karakeçili" },
  { provinceId: 71, name: "Keskin" },
  { provinceId: 71, name: "Sulakyurt" },
  { provinceId: 71, name: "Yahşihan" },
  // Batman (72)
  { provinceId: 72, name: "Merkez" },
  { provinceId: 72, name: "Beşiri" },
  { provinceId: 72, name: "Gercüş" },
  { provinceId: 72, name: "Hasankeyf" },
  { provinceId: 72, name: "Kozluk" },
  { provinceId: 72, name: "Sason" },
  // Şırnak (73)
  { provinceId: 73, name: "Merkez" },
  { provinceId: 73, name: "Beytüşşebap" },
  { provinceId: 73, name: "Cizre" },
  { provinceId: 73, name: "Güçlükonak" },
  { provinceId: 73, name: "İdil" },
  { provinceId: 73, name: "Silopi" },
  { provinceId: 73, name: "Uludere" },
  // Bartın (74)
  { provinceId: 74, name: "Merkez" },
  { provinceId: 74, name: "Amasra" },
  { provinceId: 74, name: "Kurucaşile" },
  { provinceId: 74, name: "Ulus" },
  // Ardahan (75)
  { provinceId: 75, name: "Merkez" },
  { provinceId: 75, name: "Çıldır" },
  { provinceId: 75, name: "Damal" },
  { provinceId: 75, name: "Göle" },
  { provinceId: 75, name: "Hanak" },
  { provinceId: 75, name: "Posof" },
  // Iğdır (76)
  { provinceId: 76, name: "Merkez" },
  { provinceId: 76, name: "Aralık" },
  { provinceId: 76, name: "Karakoyunlu" },
  { provinceId: 76, name: "Tuzluca" },
  // Yalova (77)
  { provinceId: 77, name: "Merkez" },
  { provinceId: 77, name: "Altınova" },
  { provinceId: 77, name: "Armutlu" },
  { provinceId: 77, name: "Çınarcık" },
  { provinceId: 77, name: "Çiftlikköy" },
  { provinceId: 77, name: "Termal" },
  // Karabük (78)
  { provinceId: 78, name: "Merkez" },
  { provinceId: 78, name: "Eflani" },
  { provinceId: 78, name: "Eskipazar" },
  { provinceId: 78, name: "Ovacık" },
  { provinceId: 78, name: "Safranbolu" },
  { provinceId: 78, name: "Yenice" },
  // Kilis (79)
  { provinceId: 79, name: "Merkez" },
  { provinceId: 79, name: "Elbeyli" },
  { provinceId: 79, name: "Musabeyli" },
  { provinceId: 79, name: "Polateli" },
  // Osmaniye (80)
  { provinceId: 80, name: "Merkez" },
  { provinceId: 80, name: "Bahçe" },
  { provinceId: 80, name: "Düziçi" },
  { provinceId: 80, name: "Hasanbeyli" },
  { provinceId: 80, name: "Kadirli" },
  { provinceId: 80, name: "Sumbas" },
  { provinceId: 80, name: "Toprakkale" },
  // Düzce (81)
  { provinceId: 81, name: "Merkez" },
  { provinceId: 81, name: "Akçakoca" },
  { provinceId: 81, name: "Cumayeri" },
  { provinceId: 81, name: "Çilimli" },
  { provinceId: 81, name: "Gölyaka" },
  { provinceId: 81, name: "Gümüşova" },
  { provinceId: 81, name: "Kaynaşlı" },
  { provinceId: 81, name: "Yığılca" },
];

// Slug oluştur (Türkçe karakterleri önce değiştir, sonra lowercase)
function createSlug(name: string): string {
  return name
    .replace(/Ğ/g, "g")
    .replace(/Ü/g, "u")
    .replace(/Ş/g, "s")
    .replace(/İ/g, "i")
    .replace(/Ö/g, "o")
    .replace(/Ç/g, "c")
    .replace(/ğ/g, "g")
    .replace(/ü/g, "u")
    .replace(/ş/g, "s")
    .replace(/ı/g, "i")
    .replace(/ö/g, "o")
    .replace(/ç/g, "c")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Seed fonksiyonu
export async function seedTurkeyLocations(prisma: {
  city: { create: (args: { data: { name: string; slug: string } }) => Promise<{ id: string; name: string }> };
  district: { create: (args: { data: { name: string; slug: string; cityId: string } }) => Promise<{ id: string }> };
}) {
  console.log("Seeding Turkey locations (81 provinces, ~970 districts)...");
  
  // İlleri oluştur ve ID'lerini sakla
  const cityMap = new Map<number, string>();
  
  for (const province of TURKEY_PROVINCES) {
    const city = await prisma.city.create({
      data: { name: province.name, slug: createSlug(province.name) },
    });
    cityMap.set(province.id, city.id);
    console.log(`  + ${province.name}`);
  }
  
  // İlçeleri oluştur
  let districtCount = 0;
  for (const district of TURKEY_DISTRICTS) {
    const cityId = cityMap.get(district.provinceId);
    if (cityId) {
      await prisma.district.create({
        data: {
          name: district.name,
          slug: createSlug(district.name),
          cityId,
        },
      });
      districtCount++;
    }
  }
  
  console.log(`Turkey locations seeded: ${TURKEY_PROVINCES.length} provinces, ${districtCount} districts`);
  return { provinceCount: TURKEY_PROVINCES.length, districtCount };
}
